name: 05 - 1 - Event Filters and Activty Types
on: 
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a PR is opend or synchronized AND base bracnh is main"


