name: 02 -Workflow Events
on: 
    # push:
    # pull_request:
    workflow_dispatch:
    # schedule:
    #    - cron: '*/4 * * * *'  # Runs daily at 14:39 IST (IST is UTC+5:30; 14:40 IST = 09:10 UTC, but GitHub Actions cron only supports minute precision, so use 09:10 UTC for 14:40 IST)
jobs: 
    echo-job:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Job
              run: echo "This is a workflow triggered by a push event.${{ github.event_name }}}"
