name: 06 - Contexts
on: push
jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: Display information
              run: |
                echo "Repository: ${{ github.repository }}"
                echo "Event Name: ${{ github.event_name }}"
                echo "SHA: ${{ github.sha }}"
                echo "Ref: ${{ github.ref }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Job: ${{ github.job }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run Number: ${{ github.run_number }}"
                echo "Event Path: ${{ github.event_path }}"
                echo "Workspace: ${{ github.workspace }}"
                echo "Action: ${{ github.action }}"
                echo "Head Ref: ${{ github.head_ref }}"
                echo "Base Ref: ${{ github.base_ref }}"