name: 10 - Controlling the Execution Flow
on:
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                type: boolean
                description: 'Do the unit tests pass?'
                default: true
jobs: 
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: List and Build
              run: echo "Linting and Building the Project"
    job-2:
        runs-on: ubuntu-latest
        steps:
            - name: Running Unit Tests
              run: echo "Run Unit Tests"
            - name: Failing Tests
              if: ${{ !inputs.pass-unit-tests}}
              run: exit 1
    job-3:
        runs-on: ubuntu-latest
        needs: [job-1, job-2]
        steps:
            - name: Deploying toNon-Production
              run: echo "Deploying to Non-Production Environment"
    job-4:
        runs-on: ubuntu-latest
        needs: job-3
        steps:
            - name: Deploying to Production
              run: echo "Deploying to Production Environment"

    job-5:
        runs-on: ubuntu-latest
        needs: [job-1, job-2, job-3, job-4]
        steps:
            - name: Final Notification
              run: echo "All jobs completed successfully!"